/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AssetAgreementRouteImport } from './routes/asset-agreement'
import { Route as AssetRouteImport } from './routes/asset'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetAgreementRoute = AssetAgreementRouteImport.update({
  id: '/asset-agreement',
  path: '/asset-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetRoute = AssetRouteImport.update({
  id: '/asset',
  path: '/asset',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asset': typeof AssetRoute
  '/asset-agreement': typeof AssetAgreementRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asset': typeof AssetRoute
  '/asset-agreement': typeof AssetAgreementRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asset': typeof AssetRoute
  '/asset-agreement': typeof AssetAgreementRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asset'
    | '/asset-agreement'
    | '/verify-email'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/asset' | '/asset-agreement' | '/verify-email' | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/asset'
    | '/asset-agreement'
    | '/verify-email'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetRoute: typeof AssetRoute
  AssetAgreementRoute: typeof AssetAgreementRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset-agreement': {
      id: '/asset-agreement'
      path: '/asset-agreement'
      fullPath: '/asset-agreement'
      preLoaderRoute: typeof AssetAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset': {
      id: '/asset'
      path: '/asset'
      fullPath: '/asset'
      preLoaderRoute: typeof AssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetRoute: AssetRoute,
  AssetAgreementRoute: AssetAgreementRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
